CREATE TABLE results
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_id BIGINT,
    subject_id BIGINT,
    score      DOUBLE PRECISION,
    CONSTRAINT pk_results PRIMARY KEY (id)
);

CREATE TABLE students
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    registration_number   VARCHAR(255)                            NOT NULL,
    foreign_language_code VARCHAR(255),
    CONSTRAINT pk_students PRIMARY KEY (id)
);

CREATE TABLE subjects
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_subjects PRIMARY KEY (id)
);

ALTER TABLE students
    ADD CONSTRAINT uc_students_registrationnumber UNIQUE (registration_number);

ALTER TABLE results
    ADD CONSTRAINT FK_RESULTS_ON_STUDENT FOREIGN KEY (student_id) REFERENCES students (id);

ALTER TABLE results
    ADD CONSTRAINT FK_RESULTS_ON_SUBJECT FOREIGN KEY (subject_id) REFERENCES subjects (id);